version: '3.4'

services:
  fpm:
    image: "digitalspacestudio/orophp:${PHP_VERSION-7.4}"
    user: root
    volumes:
      - 'magento-fpm-appcode:/var/www'
      - 'magento-fpm-npm:/var/www/.npm'
      - 'magento-fpm-composer:/var/www/.composer'
      - './fpm/php-fpm.conf:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/php-fpm.conf:ro'
      - './fpm/php.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/php.ini:ro'
      - './fpm/prepend.php:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/prepend.php:ro'
      - './fpm/msmtprc:/home/linuxbrew/.msmtprc:ro'
      - './fpm/entrypoint.sh:/entrypoint.sh:ro'
    entrypoint: '/entrypoint.sh'
    working_dir: '/var/www'
    networks:
      - 'magento'
    environment:
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_HOME=/var/www/.composer'
      - 'COMPOSER_AUTH=$COMPOSER_AUTH'
    networks:
      - 'magento'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"
      start_period: 60s
      interval: 5s

  cli:
    image: "digitalspacestudio/orophp:${PHP_VERSION-7.4}"
    user: root
    volumes:
      - 'magento-fpm-appcode:/var/www'
      - 'magento-fpm-npm:/var/www/.npm'
      - 'magento-fpm-composer:/var/www/.composer'
      - './cli/php.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/php.ini:ro'
      - './cli/ext-xdebug.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/conf.d/ext-xdebug.ini:ro'
      - './fpm/prepend.php:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-7.4}/prepend.php:ro'
      - './fpm/msmtprc:/home/linuxbrew/.msmtprc:ro'
      - './cli/entrypoint.sh:/entrypoint.sh:ro'
    entrypoint: '/entrypoint.sh'
    working_dir: '/var/www'
    networks:
      - 'magento'
    environment:
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_HOME=/var/www/.composer'
      - 'COMPOSER_AUTH=$COMPOSER_AUTH'
    networks:
      - 'magento'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy

  xhgui:
    image: "xhgui/xhgui:0.18.1"
    volumes:
      - ./xhgui/config:/var/www/xhgui/config
      - ./xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${DOCKER_PORT_XHGUI:-30281}:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 'magento'
    restart: on-failure:3
    healthcheck:
      test: nc -vz -w 1 localhost 80
      start_period: 30s
      interval: 5s

  mail:
    image: "mailhog/mailhog"
    ports:
      - "${DOCKER_PORT_MAIL_HTTP:-38225}:8025"
    networks:
      - 'magento'
    restart: on-failure:3
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 5s

  mongodb:
    image: percona/percona-server-mongodb:4.4
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "27017"
    networks:
      - 'magento'
    restart: on-failure:3
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui
      start_period: 30s
      interval: 10s

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2-magento2'
    build: "elasticsearch"
    volumes:
      - "magento-elasticsearch-data:/usr/share/elasticsearch/data"
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms256m -Xmx2048m}'
      discovery.type: 'single-node'
    ports:
      - '9200'
    networks:
      - 'magento'
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9200"
      start_period: 15s
      interval: 5s
      retries: 5

  nginx:
    image: 'crunchgeek/nginx-pagespeed'
    environment:
      NGINX_GEOIP: 'off'
      NGINX_PAGESPEED: 'on'
      NGINX_PAGESPEED_IMG: 'on'
      NGINX_PAGESPEED_JS: 'on'
      NGINX_PAGESPEED_CSS: 'on'
      NGINX_PAGESPEED_STORAGE: 'files'
    depends_on:
      fpm:
        condition: service_healthy
    ports:
      - '${DOCKER_PORT_HTTP:-30280}:80'
    volumes:
      - './www:/var/www:ro'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/pagespeed.conf:/etc/nginx/pagespeed.conf:ro'
    networks:
      - 'magento'
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/80"
      start_period: 30s
      interval: 5s

networks:
  magento:

volumes:
  magento-fpm-appcode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/www"
  magento-fpm-npm:
    driver: local
  magento-fpm-composer:
    driver: local
  magento-elasticsearch-data:
    driver: local
