version: '3.4'

volumes:
  magento-fpm-appcode:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,sync,tcp,rw,noacl,hard,intr,nfsvers=3
      device: ":${PWD}/www"
